---
- name: create AWS VPC
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - vpc
    - ec2
  tasks:
    - name: Refresh inventory
      meta: refresh_inventory

#- name: Nginx Instale
#  hosts: tag_role_cent-web
#  become: true
#  gather_facts: False
#  roles:
#    - nginx
